// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Faz login via Supabase e retorna tokens (access_token, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credenciais",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/formularios": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Lista todos os Formulários Modelo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por ONG",
                        "name": "ong_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.FormularioListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cria um formulário com campos configuráveis para uso na adoção de pets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Cria um novo Formulário Modelo",
                "parameters": [
                    {
                        "description": "Novo Formulário",
                        "name": "formulario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateFormularioModeloInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.FormularioModelo"
                        }
                    }
                }
            }
        },
        "/api/v1/formularios/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Busca um Formulário Modelo pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FormularioModelo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Atualiza o nome de um Formulário Modelo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "formulario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateFormularioModeloInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.FormularioModelo"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove o formulário e todos os campos em cascata",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Remove um Formulário Modelo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/formularios/{id}/campos": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Adiciona um Campo ao Formulário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo Campo",
                        "name": "campo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateCampoInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CampoFormulario"
                        }
                    }
                }
            }
        },
        "/api/v1/formularios/{id}/campos/{campoId}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Atualiza um Campo do Formulário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do Campo",
                        "name": "campoId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "campo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateCampoInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CampoFormulario"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FormularioModelo"
                ],
                "summary": "Remove um Campo do Formulário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Formulário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do Campo",
                        "name": "campoId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/ongs": {
            "get": {
                "description": "Retorna todas as ONGs cadastradas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ONG"
                ],
                "summary": "Lista todas as ONGs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.OngListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cria uma ONG no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ONG"
                ],
                "summary": "Cria uma nova ONG",
                "parameters": [
                    {
                        "description": "Nova ONG",
                        "name": "ong",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateOngInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Ong"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/ongs/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Atualiza os dados de uma ONG pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ONG"
                ],
                "summary": "Atualiza uma ONG existente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da ONG",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "ong",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateOngInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "ong": {
                                    "$ref": "#/definitions/models.Ong"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove uma ONG pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ONG"
                ],
                "summary": "Remove uma ONG",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da ONG",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pedidos-adocao": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PedidoAdocao"
                ],
                "summary": "Lista todos os Pedidos de Adoção",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por ONG",
                        "name": "ong_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por Pet",
                        "name": "pet_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.PedidoAdocaoListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cria o pedido com as respostas ao formulário vinculado ao Pet.\nAs respostas são validadas contra a configuração de cada campo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PedidoAdocao"
                ],
                "summary": "Cria um novo Pedido de Adoção",
                "parameters": [
                    {
                        "description": "Novo Pedido",
                        "name": "pedido",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreatePedidoAdocaoInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.PedidoAdocaoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pedidos-adocao/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PedidoAdocao"
                ],
                "summary": "Busca um Pedido de Adoção pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pedido",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PedidoAdocaoDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PedidoAdocao"
                ],
                "summary": "Remove um Pedido de Adoção",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pedido",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pedidos-adocao/{id}/status": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Status válidos: pendente, aprovado, rejeitado, cancelado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PedidoAdocao"
                ],
                "summary": "Atualiza o status de um Pedido de Adoção",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pedido",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateStatusPedidoAdocaoInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PedidoAdocaoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pets": {
            "get": {
                "description": "Retorna todos os pets cadastrados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Lista todos os Pets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por nome",
                        "name": "nome",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por espécie",
                        "name": "especie",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por porte",
                        "name": "porte",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por região",
                        "name": "regiao",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por ONG",
                        "name": "ong_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.PetListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cria um Pet no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Cria um novo Pet",
                "parameters": [
                    {
                        "description": "Novo Pet",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreatePetInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Pet"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pets/{id}": {
            "get": {
                "description": "Retorna um Pet específico pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Busca um Pet pelo ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pet",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Pet"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Atualiza os dados de um Pet pelo ID (não atualiza imagens)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Atualiza um Pet existente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pet",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualização",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreatePetInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "pet": {
                                    "$ref": "#/definitions/models.Pet"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove um Pet pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Remove um Pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pet",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pets/{id}/imagens": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Faz upload de até 5 imagens para o Pet pelo ID (usando Supabase)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Adiciona imagens a um Pet existente",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pet",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagens do Pet (até 5)",
                        "name": "imagens",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "pet": {
                                    "$ref": "#/definitions/models.Pet"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/pets/{id}/imagens/{imageId}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove uma imagem específica de um Pet pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "Remove uma imagem de um Pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Pet",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da Imagem",
                        "name": "imageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                },
                                "pet": {
                                    "$ref": "#/definitions/models.Pet"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CampoConfiguracao": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "descricao": {
                    "description": "texto de ajuda abaixo do campo",
                    "type": "string"
                },
                "label": {
                    "description": "Apresentação",
                    "type": "string"
                },
                "max": {
                    "description": "max de caracteres (texto) ou valor (numero)",
                    "type": "integer"
                },
                "max_valor": {
                    "description": "para tipo numero",
                    "type": "number"
                },
                "min": {
                    "description": "min de caracteres (texto) ou valor (numero)",
                    "type": "integer"
                },
                "min_valor": {
                    "description": "para tipo numero",
                    "type": "number"
                },
                "obrigatorio": {
                    "description": "Validações",
                    "type": "boolean"
                },
                "opcoes": {
                    "description": "Opções (apenas para select, radio, checkbox)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "placeholder": {
                    "description": "ex: \"Digite seu nome\"",
                    "type": "string"
                },
                "regex": {
                    "type": "string"
                },
                "tipo": {
                    "description": "Tipo",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TipoCampo"
                        }
                    ]
                }
            }
        },
        "models.CampoFormulario": {
            "type": "object",
            "properties": {
                "configuracao": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "formulario_modelo_id": {
                    "description": "ponteiro = nullable",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "ordem": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.CampoFormularioDTO": {
            "type": "object",
            "properties": {
                "configuracao": {
                    "$ref": "#/definitions/models.CampoConfiguracao"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "ordem": {
                    "type": "integer"
                }
            }
        },
        "models.FormularioModelo": {
            "type": "object",
            "properties": {
                "campos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CampoFormulario"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "ong_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Ong": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "endereco": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "nome_responsavel": {
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.PedidoAdocaoDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ong_id": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "respostas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.RespostaFormularioDTO"
                    }
                },
                "status": {
                    "$ref": "#/definitions/models.PedidoAdocaoStatus"
                }
            }
        },
        "models.PedidoAdocaoStatus": {
            "type": "string",
            "enum": [
                "pendente",
                "aprovado",
                "rejeitado",
                "cancelado"
            ],
            "x-enum-varnames": [
                "PedidoAdocaoPendente",
                "PedidoAdocaoAprovado",
                "PedidoAdocaoRejeitado",
                "PedidoAdocaoCancelado"
            ]
        },
        "models.Pet": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "especie": {
                    "type": "string"
                },
                "formulario_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "idade": {
                    "type": "integer"
                },
                "imagens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PetImage"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "ong_id": {
                    "type": "string"
                },
                "peso": {
                    "type": "number"
                },
                "porte": {
                    "type": "string"
                },
                "raca": {
                    "type": "string"
                },
                "regiao": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.PetStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.PetImage": {
            "type": "object",
            "properties": {
                "pet_id": {
                    "type": "string"
                },
                "position": {
                    "description": "ordem no frontend",
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.PetStatus": {
            "type": "string",
            "enum": [
                "adopted",
                "available",
                "draft"
            ],
            "x-enum-varnames": [
                "PetAdopted",
                "PetAvailable",
                "PetDraft"
            ]
        },
        "models.RespostaFormularioDTO": {
            "type": "object",
            "properties": {
                "campo": {
                    "$ref": "#/definitions/models.CampoFormularioDTO"
                },
                "id": {
                    "type": "string"
                },
                "valor": {
                    "type": "string"
                }
            }
        },
        "models.TipoCampo": {
            "type": "string",
            "enum": [
                "texto",
                "numero",
                "select",
                "radio",
                "checkbox",
                "textarea",
                "email",
                "telefone",
                "data"
            ],
            "x-enum-varnames": [
                "TipoCampoTexto",
                "TipoCampoNumero",
                "TipoCampoSelect",
                "TipoCampoRadio",
                "TipoCampoCheckbox",
                "TipoCampoTextarea",
                "TipoCampoEmail",
                "TipoCampoTelefone",
                "TipoCampoData"
            ]
        },
        "v1.CreateCampoInput": {
            "type": "object",
            "properties": {
                "configuracao": {
                    "$ref": "#/definitions/models.CampoConfiguracao"
                },
                "nome": {
                    "type": "string"
                },
                "ordem": {
                    "type": "integer"
                }
            }
        },
        "v1.CreateFormularioModeloInput": {
            "type": "object",
            "properties": {
                "campos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.CreateCampoInput"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "ong_id": {
                    "type": "string"
                }
            }
        },
        "v1.CreateOngInput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "a@b.com"
                },
                "endereco": {
                    "type": "string",
                    "example": "Rua A"
                },
                "nome": {
                    "type": "string",
                    "example": "Minha ONG"
                },
                "nome_responsavel": {
                    "type": "string",
                    "example": "Fulano"
                },
                "telefone": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "v1.CreatePedidoAdocaoInput": {
            "type": "object",
            "properties": {
                "ong_id": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "respostas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.CreateRespostaInput"
                    }
                }
            }
        },
        "v1.CreatePetInput": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "especie": {
                    "type": "string"
                },
                "formulario_id": {
                    "type": "string"
                },
                "idade": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "ong_id": {
                    "type": "string"
                },
                "peso": {
                    "type": "number"
                },
                "porte": {
                    "type": "string"
                },
                "raca": {
                    "type": "string"
                },
                "regiao": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.PetStatus"
                }
            }
        },
        "v1.CreateRespostaInput": {
            "type": "object",
            "properties": {
                "campo_formulario_id": {
                    "type": "string"
                },
                "valor": {
                    "type": "string"
                }
            }
        },
        "v1.FormularioListResponse": {
            "type": "object",
            "properties": {
                "dados": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FormularioModelo"
                    }
                },
                "proxima_pagina": {
                    "type": "boolean"
                },
                "total_paginas": {
                    "type": "integer"
                },
                "total_registros": {
                    "type": "integer"
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "v1.OngListResponse": {
            "type": "object",
            "properties": {
                "dados": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Ong"
                    }
                },
                "proxima_pagina": {
                    "type": "boolean"
                },
                "total_paginas": {
                    "type": "integer"
                },
                "total_registros": {
                    "type": "integer"
                }
            }
        },
        "v1.PedidoAdocaoListResponse": {
            "type": "object",
            "properties": {
                "dados": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PedidoAdocaoDTO"
                    }
                },
                "proxima_pagina": {
                    "type": "boolean"
                },
                "total_paginas": {
                    "type": "integer"
                },
                "total_registros": {
                    "type": "integer"
                }
            }
        },
        "v1.PetListResponse": {
            "type": "object",
            "properties": {
                "dados": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Pet"
                    }
                },
                "proxima_pagina": {
                    "type": "boolean"
                },
                "total_paginas": {
                    "type": "integer"
                },
                "total_registros": {
                    "type": "integer"
                }
            }
        },
        "v1.UpdateFormularioModeloInput": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateStatusPedidoAdocaoInput": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/models.PedidoAdocaoStatus"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OngPet API",
	Description:      "API para gerenciar ONGs e pets",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
